# Generated by Django 5.0.6 on 2024-05-17 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='fecha_adopcion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
